apiVersion: v2
name: vlm-node
description: A Helm chart for compute nodes (SLAM, task-timing, etc.)
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "15.4.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
